[build]
  publish = "client/dist"
  command = "cd client && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://blend-dessert-co-api.onrender.com"
